### PR TITLE
Cmv condition nr 13

### PR DESCRIPTION
**Pull request by Dajamante**
closing #CMV condition nr 13

### CODE REVIEW

**Comment by gmm97** [comment]
Same issue as #21 
Please refer there

**Review by gmm97 — CHANGES_REQUESTED** [review]
1) Change function name to condition 13
2) Logic is incorrect, refer to #21

**Comment by jacobmimms** [comment]
I adjusted the logic, but also copied cmv_condition_8 into the branch to make writing cmv_13 easier, as you can just write the additional condition needed for cmv_13 to pass then return cmv_condition_8. Must resolve this while merging.

**Review by ztick — APPROVED** [review]
Nice LGTM

**Pull request merged**
